### ISSUE TITLE
Incorrect Value Used in Code for DotNet Tutorial

### ISSUE THREAD

**Issue by TaighHawkins** [microsoftgraph/microsoft-graph-training#116]
On the page: https://learn.microsoft.com/en-us/graph/tutorials/dotnet?tabs=aad&tutorial-step=3

![image](https://user-images.githubusercontent.com/10461647/192553659-dc2b1b71-45a7-4b98-8af8-dc5dcad32312.png)
The line:
``` c#
_deviceCodeCredential = new DeviceCodeCredential(deviceCodePrompt,
        settings.AuthTenant, settings.ClientId);
```
is incorrect and should instead read:
``` c#
_deviceCodeCredential = new DeviceCodeCredential(deviceCodePrompt,
            settings.TenantId, settings.ClientId);
```
Otherwise it doesn't tie to the tenant you're trying to log into.

I looked for the code directly to make a PR for it but was unable to locate it.

**Comment by jasonjoh** [comment]
It is correct as written, though it's admittedly confusing. We're looking into refactoring this to be more intuitive.

From https://learn.microsoft.com/graph/tutorials/dotnet?tabs=aad&tutorial-step=2:

<html>
<body>
<p style="box-sizing: inherit; outline-color: inherit; margin: 1rem 0px 0px; padding: 0px; overflow-wrap: break-word; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Update the values according to the following table.</p><div class="has-inner-focus" style="box-sizing: inherit; outline-color: inherit; color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(23, 23, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Setting | Value
-- | --
clientId | The client ID of your app registration
authTenant | If you chose the option to only allow users in your organization to sign in, change this value to your tenant ID. Otherwise leave as common.

</div>
</body>
</html>

**Comment by TaighHawkins** [comment]
Ah, yes, I missed that. Definitely not as clean as it could be, but thanks for clarifying.
