### ISSUE TITLE
confusing

### ISSUE THREAD

**Issue by RoYoMi** [microsoftgraph/microsoft-graph-training#121]
In the section setting up appSettings.js, the document says the following statements:

>   'tenantId': 'YOUR_TENANT_ID_HERE_IF_USING_APP_ONLY',
>   'authTenant': 'common',
> 
> 
> authTenant	If you chose the option to only allow users in your organization to sign in, change this value to your tenant ID. Otherwise leave as common.

On the previous page we configured the in Azure to support user authentication. 
These for tenantId and authTenant are confusing. Do we:
1. Leave tenantid blank because we're using user authentication?
2. add the "tenant id" to authTenant?

Side note:
I've been struggling getting anything to work with Azure + Javascript for several weeks now. By itself it's a convoluted topic made more confusing because my organization decided to make it super complicated.

Azure portal App Registration page shows the following names `Application (client) ID` and `Directory (tenant) ID`. To further help avoid confusion it would be nice if the names in the document exactly matched where we get the information.

**Comment by jasonjoh** [comment]
That's great feedback! We've done some simplification and streamlining of the tutorial to address this.

To answer your question:

1. Yes the `tenantId` value isn't used for user auth in the tutorial that you're currently seeing. In the revised, we've eliminated `authTenant` and there is now only `tenantId`.
2. If you registered as a multi-tenant app, leave it as `common`. Otherwise, set it to your tenant ID.

**Comment by jasonjoh** [comment]
Revised tutorial is live: https://learn.microsoft.com/graph/tutorials/javascript

Hopefully the revision is clearer.
