### ISSUE TITLE
Got a token after device code login, now what?

### ISSUE THREAD

**Issue by BloodyRain2k** [microsoftgraph/microsoft-graph-training#123]
I don't know if I managed to overlook something here, but I don't see any part in the tutorial or the code it shows that actually handles the token after the device code login.

There's code to show it, but that's it.

And I'm also not sure if I'm misinterpreting the tutorial but after the "Add user authentication" it acts as if we can just restart the program and it will NOT ask for a new device code login the next time. Which is what I'm running into.

I'd really like to know what I am supposed to do with the token and how I am supposed to reuse it, IF I am even supposed to be able to do so. The tutorial isn't even clear about this part.

**Comment by jasonjoh** [comment]
Showing the token is basically to prove that the authentication worked! In a real app, there's no need to display the token.

With our Graph SDK, you don't need to manage tokens at all. The `DeviceCodeCredential` is wired to the Graph client object, and it handles requesting tokens as you make API calls.

When you restart the program, it will re-prompt you. That's because by default, the Azure Identity library uses an in-memory cache for tokens. Depending on which language you're working with, they provide mechanisms for you to allow it to cache to some persistent storage, which would eliminate the repeated prompts.

As for the "now what?" - if you've gotten a token, you should be good to proceed with the next steps of the tutorial.

**Comment by BloodyRain2k** [comment]
I've looked into the whole thing a bit more and by now have a slightly better understanding how it works. 
But as someone who literally just started with TypeScript and Graph I felt a little lost when I followed the tutorial and did manage to get the token but had to re-do the whole process each time I changed anything in the code.

I also managed to miss that this tutorial is available in more versions than TypeScript, that one's totally on me...

By now I know that the tokens don't even have a long lifetime in the first place and that they can't be reused anyways.
But since the tutorial just moved on without pointing out that it's normal to have re-doing the device code process each update, nor explaining why we're not storing the token in some form to get around that, I felt like I was missing something fundamental which threw me off.
